// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneStop.Persistence;

#nullable disable

namespace OneStop.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120072248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneStop.Domain.Modules.Inventory.StockMutation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReferenceDocument")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("Timestamp");

                    b.ToTable("StockMutations", (string)null);
                });

            modelBuilder.Entity("OneStop.Domain.Modules.Production.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastPriceUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("OneStop.Domain.Modules.Production.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CachedCostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastCostCalculation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OutputQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("OneStop.Domain.Modules.Inventory.StockMutation", b =>
                {
                    b.OwnsOne("OneStop.Domain.Modules.Production.Unit", "Unit", b1 =>
                        {
                            b1.Property<Guid>("StockMutationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Unit_Code");

                            b1.Property<decimal>("ConversionFactorToBase")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Unit_Factor");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Unit_Name");

                            b1.HasKey("StockMutationId");

                            b1.ToTable("StockMutations");

                            b1.WithOwner()
                                .HasForeignKey("StockMutationId");
                        });

                    b.Navigation("Unit")
                        .IsRequired();
                });

            modelBuilder.Entity("OneStop.Domain.Modules.Production.Ingredient", b =>
                {
                    b.OwnsOne("OneStop.Domain.Modules.Production.Unit", "StockUnit", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("StockUnit_Code");

                            b1.Property<decimal>("ConversionFactorToBase")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("StockUnit_Factor");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("StockUnit_Name");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("StockUnit")
                        .IsRequired();
                });

            modelBuilder.Entity("OneStop.Domain.Modules.Production.Recipe", b =>
                {
                    b.OwnsOne("OneStop.Domain.Modules.Production.Unit", "OutputUnit", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("OutputUnit_Code");

                            b1.Property<decimal>("ConversionFactorToBase")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("OutputUnit_Factor");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("OutputUnit_Name");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("OneStop.Domain.Modules.Production.RecipeItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ComponentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("RecipeId", "Id");

                            b1.ToTable("RecipeItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");

                            b1.OwnsOne("OneStop.Domain.Modules.Production.Unit", "Unit", b2 =>
                                {
                                    b2.Property<Guid>("RecipeItemRecipeId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("RecipeItemId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("Unit_Code");

                                    b2.Property<decimal>("ConversionFactorToBase")
                                        .HasColumnType("decimal(18,4)")
                                        .HasColumnName("Unit_Factor");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("Unit_Name");

                                    b2.HasKey("RecipeItemRecipeId", "RecipeItemId");

                                    b2.ToTable("RecipeItems");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipeItemRecipeId", "RecipeItemId");
                                });

                            b1.Navigation("Unit")
                                .IsRequired();
                        });

                    b.Navigation("Items");

                    b.Navigation("OutputUnit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
